
spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# 파라미터 찍어준다.
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
#            sql: trace